name: Build and publish docker image

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: eg-default
    name: Builds the image and publishes to docker hub
    env:
      KUMO_RELEASE_REPO: expediagroup-docker-internal-local.artylab.expedia.biz
      APP_NAME: delete-abandoned-branches
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Login
        uses: actions/docker-login-action@v1
        with:
          registry: kumo-docker-release-local.artylab.expedia.biz
          username: ${{ secrets.ARTYLAB_USERNAME }}
          password: ${{ secrets.ARTYLAB_API_KEY }}

      - name: Grab version
        run: echo VERSION="$(cat .version)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: actions/docker-metadata-action@v3
        with:
          images: ${{ env.KUMO_RELEASE_REPO }}/library/${{ env.APP_NAME }}
          tags: ${{ env.VERSION }}

      - name: Build Docker image
        uses: actions/docker-build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
